# Generated by Django 2.2 on 2021-04-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/blank', null=True, upload_to='images/'),
        ),
    ]
