# Generated by Django 2.2 on 2021-04-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0002_auto_20210413_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media\\images\x08lank.jpg', null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('message_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='RaceApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('comment_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_comment', to='RaceApp.User')),
                ('comment_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_comment', to='RaceApp.Message')),
            ],
        ),
    ]
