# Generated by Django 2.2 on 2021-04-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0003_auto_20210415_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images\x08lank.jpg', null=True, upload_to='images/'),
        ),
    ]
