# Generated by Django 2.2 on 2021-04-15 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0005_auto_20210415_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='date',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('distance_goal', models.FloatField()),
                ('sunday_completed', models.BooleanField(default=False)),
                ('monday_completed', models.BooleanField(default=False)),
                ('tuesday_completed', models.BooleanField(default=False)),
                ('wednesday_completed', models.BooleanField(default=False)),
                ('thursday_completed', models.BooleanField(default=False)),
                ('friday_completed', models.BooleanField(default=False)),
                ('saturday_completed', models.BooleanField(default=False)),
                ('sunday', models.FloatField()),
                ('monday', models.FloatField()),
                ('tuesday', models.FloatField()),
                ('wednesday', models.FloatField()),
                ('thursday', models.FloatField()),
                ('friday', models.FloatField()),
                ('sat', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race', to='RaceApp.User')),
            ],
        ),
    ]
